#!/bin/bash

REPO_NAME_FILE="${0%/*}/profiles/repo_name"
REPO_NAME="$(cat "${REPO_NAME_FILE}")"

repoman manifest
egencache --repo="${REPO_NAME}" --update-use-local-desc
egencache --repo="${REPO_NAME}" --update-pkg-desc-index
sudo egencache --repo="${REPO_NAME}" --update
chown -R --reference=. *
repoman full -d
