/* automatically generated from lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAccelGroup\" id=\"a11y_accelgroup\"/><object class=\"GtkAccelGroup\" i"
  "d=\"power_accelgroup\"/><object class=\"GtkWindow\" id=\"panel_window\""
  "><property name=\"name\">panel_window</property><property name=\"can_fo"
  "cus\">False</property><property name=\"decorated\">False</property><acc"
  "el-groups><group name=\"a11y_accelgroup\"/><group name=\"power_accelgro"
  "up\"/></accel-groups><child><object class=\"GtkHBox\" id=\"box3\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"homogeneous\">True</property><child><object"
  " class=\"GtkLabel\" id=\"hostname_label\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"halign\">start</property><property name=\"xalign\">0</property><pro"
  "perty name=\"xpad\">6</property><property name=\"label\">[hostname]</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkLabel\" id=\"clock_labe"
  "l\"><property name=\"can_focus\">False</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child><child>"
  "<object class=\"GtkMenuBar\" id=\"menubar\"><property name=\"name\">men"
  "ubar</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"halign\">end</property><"
  "property name=\"pack_direction\">rtl</property><signal name=\"key-press"
  "-event\" handler=\"menubar_key_press_cb\" swapped=\"no\"/><child><objec"
  "t class=\"GtkMenuItem\" id=\"power_menuitem\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><child type"
  "=\"submenu\"><object class=\"GtkMenu\" id=\"power_menu\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"accel_group\">power_accelgroup</property><child><obj"
  "ect class=\"GtkMenuItem\" id=\"suspend_menuitem\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"accel_path\">&lt;Login&gt;/power/suspend</property><propert"
  "y name=\"label\" translatable=\"yes\">Suspend</property><signal name=\""
  "activate\" handler=\"suspend_cb\" swapped=\"no\"/></object></child><chi"
  "ld><object class=\"GtkMenuItem\" id=\"hibernate_menuitem\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"accel_path\">&lt;Login&gt;/power/hibernate</proper"
  "ty><property name=\"label\" translatable=\"yes\">Hibernate</property><s"
  "ignal name=\"activate\" handler=\"hibernate_cb\" swapped=\"no\"/></obje"
  "ct></child><child><object class=\"GtkMenuItem\" id=\"restart_menuitem\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"accel_path\">&lt;Login&gt;/power/rest"
  "art</property><property name=\"label\" translatable=\"yes\">Restart...<"
  "/property><signal name=\"activate\" handler=\"restart_cb\" swapped=\"no"
  "\"/></object></child><child><object class=\"GtkMenuItem\" id=\"shutdown"
  "_menuitem\"><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"accel_path\">&lt;Login&gt;/power/shutdow"
  "n</property><property name=\"label\" translatable=\"yes\">Shut Down...<"
  "/property><signal name=\"activate\" handler=\"shutdown_cb\" swapped=\"n"
  "o\"/></object></child></object></child></object></child><child><object "
  "class=\"GtkMenuItem\" id=\"a11y_menuitem\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><child type=\""
  "submenu\"><object class=\"GtkMenu\" id=\"a11y_menu\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"accel_group\">a11y_accelgroup</property><child><object c"
  "lass=\"GtkCheckMenuItem\" id=\"large_font_menuitem\"><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "accel_path\">&lt;Login&gt;/a11y/font</property><property name=\"label\""
  " translatable=\"yes\">Large Font</property><signal name=\"toggled\" han"
  "dler=\"a11y_font_cb\" swapped=\"no\"/></object></child><child><object c"
  "lass=\"GtkCheckMenuItem\" id=\"high_contrast_menuitem\"><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"accel_path\">&lt;Login&gt;/a11y/contrast</property><property name=\""
  "label\" translatable=\"yes\">High Contrast</property><signal name=\"tog"
  "gled\" handler=\"a11y_contrast_cb\" swapped=\"no\"/></object></child><c"
  "hild><object class=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\"><prope"
  "rty name=\"use_action_appearance\">False</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"accel_path\">&lt;Login&gt;/a11y/keyboard</property><proper"
  "ty name=\"label\" translatable=\"yes\">On Screen Keyboard</property><pr"
  "operty name=\"use_underline\">True</property><signal name=\"toggled\" h"
  "andler=\"a11y_keyboard_cb\" swapped=\"no\"/></object></child></object><"
  "/child></object></child><child><object class=\"GtkMenuItem\" id=\"langu"
  "age_menuitem\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"label\">[language_code]<"
  "/property><child type=\"submenu\"><object class=\"GtkMenu\" id=\"langua"
  "ge_menu\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property></object></child></object></child><child><obj"
  "ect class=\"GtkMenuItem\" id=\"session_menuitem\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><child"
  " type=\"submenu\"><object class=\"GtkMenu\" id=\"session_menu\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property></object></child></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"pack_type\">end</property><property name=\"position\">"
  "2</property></packing></child></object></child></object><object class=\""
  "GtkListStore\" id=\"user_liststore\"><columns><column type=\"gchararray"
  "\"/><column type=\"gchararray\"/><column type=\"gint\"/></columns></obj"
  "ect><object class=\"GtkWindow\" id=\"login_window\"><property name=\"na"
  "me\">login_window</property><property name=\"can_focus\">False</propert"
  "y><property name=\"resizable\">False</property><property name=\"decorat"
  "ed\">False</property><accel-groups><group name=\"a11y_accelgroup\"/><gr"
  "oup name=\"power_accelgroup\"/></accel-groups><signal name=\"key-press-"
  "event\" handler=\"login_window_key_press_cb\" swapped=\"no\"/><child><o"
  "bject class=\"GtkVBox\" id=\"vbox2\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><child><object cla"
  "ss=\"GtkFrame\" id=\"content_frame\"><property name=\"name\">content_fr"
  "ame</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label_xalign\">0</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkTable\" id=\"table1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"margin_left\""
  ">24</property><property name=\"margin_right\">24</property><property na"
  "me=\"margin_top\">24</property><property name=\"n_rows\">3</property><p"
  "roperty name=\"n_columns\">2</property><property name=\"column_spacing\""
  ">18</property><property name=\"row_spacing\">6</property><child><object"
  " class=\"GtkComboBox\" id=\"user_combobox\"><property name=\"name\">use"
  "r_combobox</property><property name=\"width_request\">200</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"model\">user"
  "_liststore</property><signal name=\"changed\" handler=\"user_combobox_a"
  "ctive_changed_cb\" swapped=\"no\"/></object><packing><property name=\"l"
  "eft_attach\">1</property><property name=\"right_attach\">2</property><p"
  "roperty name=\"y_options\"/></packing></child><child><object class=\"Gt"
  "kEntry\" id=\"password_entry\"><property name=\"name\">prompt_entry</pr"
  "operty><property name=\"width_request\">200</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"visibility\">False</property><property name=\"invisible_"
  "char\">\342\200\242</property><property name=\"primary_icon_activatable"
  "\">False</property><property name=\"secondary_icon_activatable\">False<"
  "/property><signal name=\"activate\" handler=\"login_cb\" swapped=\"no\""
  "/><signal name=\"key-press-event\" handler=\"password_key_press_cb\" sw"
  "apped=\"no\"/></object><packing><property name=\"left_attach\">1</prope"
  "rty><property name=\"right_attach\">2</property><property name=\"top_at"
  "tach\">2</property><property name=\"bottom_attach\">3</property><proper"
  "ty name=\"y_options\"/></packing></child><child><object class=\"GtkEntr"
  "y\" id=\"username_entry\"><property name=\"name\">prompt_entry</propert"
  "y><property name=\"can_focus\">True</property><property name=\"no_show_"
  "all\">True</property><property name=\"invisible_char\">\342\200\242</pr"
  "operty><signal name=\"focus-out-event\" handler=\"username_focus_out_cb"
  "\" swapped=\"no\"/><signal name=\"key-press-event\" handler=\"username_"
  "key_press_cb\" swapped=\"no\"/></object><packing><property name=\"left_"
  "attach\">1</property><property name=\"right_attach\">2</property><prope"
  "rty name=\"top_attach\">1</property><property name=\"bottom_attach\">2<"
  "/property></packing></child><child><object class=\"GtkFrame\" id=\"user"
  "_image_border\"><property name=\"name\">user_image_border</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label_xalign\">0</property><property name"
  "=\"shadow_type\">none</property><child><object class=\"GtkImage\" id=\""
  "user_image\"><property name=\"name\">user_image</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"pixel_size\">80</property><property name=\"icon_nam"
  "e\">avatar-default</property></object></child></object><packing><proper"
  "ty name=\"bottom_attach\">3</property><property name=\"x_options\"/><pr"
  "operty name=\"y_options\"/></packing></child></object></child><child ty"
  "pe=\"label_item\"><placeholder/></child></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkAlignment\" id=\"infobar_compat\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><child><obje"
  "ct class=\"GtkLabel\" id=\"message_label\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" comments=\"This is a placeholder string and will be replac"
  "ed with a message from PAM\">[message]</property></object></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkFrame\" id=\"buttonbox_frame\"><prop"
  "erty name=\"name\">buttonbox_frame</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label_xalign\">0</property><property name=\"shadow_type\">none</"
  "property><child><object class=\"GtkHBox\" id=\"hbox2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"margin_left\">24</property><property name=\"margin_righ"
  "t\">24</property><property name=\"margin_bottom\">24</property><child><"
  "object class=\"GtkButton\" id=\"login_button\"><property name=\"label\""
  " translatable=\"yes\">Log In</property><property name=\"name\">login_bu"
  "tton</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">True<"
  "/property><signal name=\"clicked\" handler=\"login_cb\" swapped=\"no\"/"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"pack_type\">end</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"cancel_button\"><property name=\"label\" tr"
  "anslatable=\"yes\">Cancel</property><property name=\"name\">cancel_butt"
  "on</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><signal name=\"clicked\" handler=\"cancel_cb\" swapped=\"no\"/><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child></object></child><child type=\"label_item\"><placeholder/"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">2</prop"
  "erty></packing></child></object></child></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 12454u;

